name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name : Configure
      run: bash configure
      
    - name: Build
      run: make
      
    - name: Run
      run: make run
      
